apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm2
  namespace: netology
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Greetings from a netology student! </h1>
    </html>
