kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-dz-rb
  namespace: netology
subjects:
- kind: User        # kind: Group
  name: netology2   # name: ops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-dz
  apiGroup: rbac.authorization.k8s.io