apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: netology
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      name: nginx
      port: 30001
      targetPort: 80
#      nodePort: 30001
    - protocol: TCP
      name: multitool
      port: 30002
      targetPort: 1111
#      nodePort: 30002
