---
- name: clickhouse
  src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"

- name: vector
  src: git@github.com:Evgenyi26rus/vector-role.git
  scm: git
  version: "v1.0.0"

- name: lighthouse
  src: git@github.com:Evgenyi26rus/LightHouse.git
  scm: git
  version: "v1.0.0"