apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/korshunovi/Загрузки