apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
  namespace: netology
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi