---
all:
  hosts:
    nexus-01:
      ansible_host: 158.160.59.43
      ansible_user: centos
      ansible_ssh_private_key_file: ".ssh/1.pub"
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos