---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.97.163
      ansible_user: centos
      ansible_ssh_private_key_file: ".ssh/1.pub"
    jenkins-agent-01:
      ansible_host: 158.160.37.43
      ansible_user: centos
      ansible_ssh_private_key_file: ".ssh/1.pub"
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: evgenyi